name: Frontend Security Scan

on:
  push:
    branches: [main, cortex-cli]
  workflow_dispatch:

jobs:
  cortex-scan:
    uses: davesadiv/reusable-cortex-cli/.github/workflows/cortex-reusable-scan.yml@main
    with:
      image_name: "frontend-app:latest"
    secrets: inherit  # This automatically passes all repo secrets to the template
